# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b17ee1e79d3de531f63b1c33a0c917a981722457372e1b63cc7472d2de255985b4dd7ae63cd4746a6ffbc480b7f3bee4a3cacda4d5d682e4e0c2e11a5e1b1df2

test:
  secret_key_base: d26bec66123585ae70129e7a4d78d5e04af09dd73e5ce419c87ee8a1acebb2b5dd2b9777bde25c732cee95bc8880618395956fdc1ea12b277e121d13ec6d871c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
